/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Meteora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Favicon1.png" />
      </Head>
      <main className="header">
        <div style={{ width: 1440, height: 58, background: 'black' }} >
          <img style={{ width: 132.75, height: 32 }} src='/img/LogoDesktop.png' />
        </div>
      </main>
    </>
  )
}
